{"when":1723822833,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723822833,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.042s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723822833,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 22862/22864)"}
{"when":1723822833,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.008s Holotree blueprint is \"5693ac85742e7335\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723822834,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.418s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723822834,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.766s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723822834,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723822834,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723822835,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[22930:python3.10]"}
{"when":1723822835,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723822835,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723822836,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723824958,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723824958,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.052s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723824958,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 70865/70866)"}
{"when":1723824958,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.009s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723824958,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.261s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723824959,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.672s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723824959,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723824959,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723824959,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[70907:python3.10]"}
{"when":1723824968,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[70907:python3.10 71134:env]"}
{"when":1723824968,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 3 ... map[70907:python3.10 71134:bash 71138:Python]"}
{"when":1723824969,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 3 to 1 ... map[70907:python3.10]"}
{"when":1723824970,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723824970,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723824971,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723825895,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723825895,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.057s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723825895,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.006s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 92067/92068)"}
{"when":1723825895,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.009s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723825895,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.273s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723825896,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.599s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723825896,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723825896,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723825896,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[92083:python3.10]"}
{"when":1723825900,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[92083:python3.10 92206:bash]"}
{"when":1723825901,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 1 ... map[92083:python3.10]"}
{"when":1723825901,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1723825901,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723825902,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723825984,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723825984,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.049s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723825984,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.006s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 94114/94115)"}
{"when":1723825984,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.008s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723825985,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.263s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723825985,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.613s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723825985,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723825985,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723825986,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[94169:python3.10]"}
{"when":1723825990,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1723825990,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723825991,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723826233,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723826233,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.041s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723826233,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 99681/99710)"}
{"when":1723826233,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.010s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723826233,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.240s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723826234,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.599s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723826234,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723826234,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723826234,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[99738:python3.10]"}
{"when":1723826238,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 3 ... map[99738:python3.10 99840:bash 99841:Python]"}
{"when":1723826238,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1723826238,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723826239,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723826461,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723826461,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.048s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723826461,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 5145/5146)"}
{"when":1723826461,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.009s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723826461,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.263s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723826462,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.620s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723826462,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723826462,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723826463,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[5193:python3.10]"}
{"when":1723826466,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 3 ... map[5193:python3.10 5263:bash 5264:Python]"}
{"when":1723826466,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723826466,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723826467,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723826498,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723826498,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.043s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723826498,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 6019/6020)"}
{"when":1723826498,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.008s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723826498,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.254s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723826499,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.601s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723826499,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723826499,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723826499,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[6032:python3.10]"}
{"when":1723826502,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 3 ... map[6032:python3.10 6125:bash 6126:Python]"}
{"when":1723826502,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1723826502,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723826503,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723826667,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723826667,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.042s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723826667,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.006s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 9810/9811)"}
{"when":1723826667,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.007s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723826667,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.256s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723826668,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.634s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723826668,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723826668,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723826669,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[9830:python3.10]"}
{"when":1723826672,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 3 ... map[9830:python3.10 9930:bash 9931:Python]"}
{"when":1723826673,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 3 to 1 ... map[9830:python3.10]"}
{"when":1723826679,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723826679,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 0 ... map[]"}
{"when":1723826679,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723826679,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723826756,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723826756,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.040s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723826756,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 11826/11827)"}
{"when":1723826756,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.009s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723826756,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.241s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723826757,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.610s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723826757,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723826757,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723826757,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[11850:python3.10]"}
{"when":1723826761,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 3 ... map[11850:python3.10 11946:bash 11947:Python]"}
{"when":1723826761,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723826761,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723826762,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723827366,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723827366,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.048s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723827366,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.006s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 25346/25350)"}
{"when":1723827366,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.010s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723827366,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.260s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723827367,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.602s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723827367,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723827367,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723827367,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[25361:rcc]"}
{"when":1723827367,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 1 ... map[25361:python3.10]"}
{"when":1723827372,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 3 ... map[25361:python3.10 25512:bash 25513:Python]"}
{"when":1723827372,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 3 to 1 ... map[25361:python3.10]"}
{"when":1723827379,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1723827379,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723827380,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723827979,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723827979,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.048s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723827979,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 38954/38956)"}
{"when":1723827979,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.008s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723827979,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.240s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723827980,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.625s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723827980,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723827980,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723827980,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[38984:python3.10]"}
{"when":1723827980,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1723827980,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723827982,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723828709,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723828709,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.051s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723828709,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 55088/55089)"}
{"when":1723828709,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.007s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723828709,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.268s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723828710,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.593s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723828710,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723828710,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723828711,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[55140:python3.10]"}
{"when":1723828713,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1723828713,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723828714,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723828736,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723828736,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.047s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723828736,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.006s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 55723/55724)"}
{"when":1723828736,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.007s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723828737,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.246s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723828737,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.557s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723828737,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723828737,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723828738,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[55767:python3.10]"}
{"when":1723828740,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 3 ... map[55767:python3.10 55829:bash 55830:Python]"}
{"when":1723828741,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 3 to 1 ... map[55767:python3.10]"}
{"when":1723828747,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1723828747,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723828749,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723828770,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723828770,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.043s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723828770,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 56581/56582)"}
{"when":1723828770,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.007s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723828770,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.249s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723828771,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.558s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723828771,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723828771,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723828771,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[56593:python3.10]"}
{"when":1723828785,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723828785,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723828786,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723831586,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723831586,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.058s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723831586,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 19046/19047)"}
{"when":1723831586,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.007s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723831587,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.257s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723831587,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.638s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723831587,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723831587,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723831587,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[19093:rcc]"}
{"when":1723831588,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 1 ... map[19093:python3.10]"}
{"when":1723831591,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 3 ... map[19093:python3.10 19197:bash 19199:Python]"}
{"when":1723831592,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 3 to 1 ... map[19093:python3.10]"}
{"when":1723831599,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1723831599,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723831600,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723831644,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723831644,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.048s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723831644,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.007s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 20400/20403)"}
{"when":1723831644,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.007s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723831644,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.242s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723831645,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.615s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723831645,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723831645,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723831645,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[20448:rcc]"}
{"when":1723831645,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 1 ... map[20448:python3.10]"}
{"when":1723831649,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 3 ... map[20448:python3.10 20552:bash 20553:Python]"}
{"when":1723831649,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 3 to 1 ... map[20448:python3.10]"}
{"when":1723831660,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723831660,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723831661,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723832502,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723832502,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.054s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723832502,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 39394/39395)"}
{"when":1723832502,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.008s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723832503,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.611s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723832503,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.622s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723832503,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723832503,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723832504,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[39452:python3.10]"}
{"when":1723832506,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1723832506,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723832507,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723832603,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723832603,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.063s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723832603,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 41681/41682)"}
{"when":1723832603,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.012s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723832603,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.258s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723832604,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.604s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723832604,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723832604,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723832604,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[41704:python3.10]"}
{"when":1723832625,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723832625,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723832626,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723832674,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723832675,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.040s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723832675,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 43353/43354)"}
{"when":1723832675,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.017s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723832675,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.258s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723832675,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.598s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723832675,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723832675,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723832676,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[43373:python3.10]"}
{"when":1723832682,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723832682,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723832683,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723832779,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723832779,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.050s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723832779,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 45722/45741)"}
{"when":1723832779,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.006s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723832780,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.240s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723832780,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.587s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723832780,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723832780,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723832781,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[45754:python3.10]"}
{"when":1723832784,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 3 ... map[45754:python3.10 45846:bash 45847:Python]"}
{"when":1723832785,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 3 to 1 ... map[45754:python3.10]"}
{"when":1723832787,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723832787,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723832788,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723832872,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723832872,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.069s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723832872,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 47784/47785)"}
{"when":1723832872,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.006s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723832872,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.258s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723832873,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.620s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723832873,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723832873,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723832874,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[47835:python3.10]"}
{"when":1723832877,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 3 ... map[47835:python3.10 47935:bash 47936:Python]"}
{"when":1723832877,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 3 to 1 ... map[47835:python3.10]"}
{"when":1723832880,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723832880,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723832881,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723832889,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723832889,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.042s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723832889,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 48196/48197)"}
{"when":1723832889,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.006s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723832889,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.257s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723832890,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.600s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723832890,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723832890,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723832891,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[48241:python3.10]"}
{"when":1723832894,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 4 ... map[48241:python3.10 48342:bash 48343:Python 48348:Python]"}
{"when":1723832895,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 4 to 2 ... map[48241:python3.10 48348:Python]"}
{"when":1723832895,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 1 ... map[48241:python3.10]"}
{"when":1723832897,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723832897,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723832898,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723833075,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723833075,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.063s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723833075,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.006s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 52337/52338)"}
{"when":1723833075,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.013s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723833075,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.248s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723833076,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.586s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723833076,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723833076,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723833077,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[52380:python3.10]"}
{"when":1723833080,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 4 ... map[52380:python3.10 52475:bash 52476:Python 52481:python3.11]"}
{"when":1723833081,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 4 to 1 ... map[52380:python3.10]"}
{"when":1723833083,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723833083,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723833084,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723833106,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723833106,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.065s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723833106,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 53045/53046)"}
{"when":1723833106,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.006s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723833106,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.263s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723833107,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.590s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723833107,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723833107,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723833107,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[53095:python3.10]"}
{"when":1723833111,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 3 ... map[53095:python3.10 53159:bash 53160:Python]"}
{"when":1723833111,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 3 to 1 ... map[53095:python3.10]"}
{"when":1723833114,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723833114,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723833115,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723833246,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723833246,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.066s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723833246,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 56224/56225)"}
{"when":1723833246,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.009s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723833247,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.250s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723833247,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.614s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723833247,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723833247,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723833247,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[56270:rcc]"}
{"when":1723833248,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 1 ... map[56270:python3.10]"}
{"when":1723833250,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[56270:python3.10 56331:uname]"}
{"when":1723833250,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 1 ... map[56270:python3.10]"}
{"when":1723833253,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723833253,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723833254,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723833522,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723833523,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.060s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723833523,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 62400/62401)"}
{"when":1723833523,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.006s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723833523,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.257s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723833523,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.611s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723833523,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723833523,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723833524,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[62417:python3.10]"}
{"when":1723833529,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723833529,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723833530,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723833590,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723833590,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.068s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723833590,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 63929/63930)"}
{"when":1723833590,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.008s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723833590,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.265s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723833591,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.634s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723833591,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723833591,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723833592,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[63944:python3.10]"}
{"when":1723833596,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723833596,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723833597,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723833722,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723833722,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.054s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723833722,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 66870/66871)"}
{"when":1723833722,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.007s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723833722,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.246s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723833723,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.603s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723833723,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723833723,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723833724,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[66896:python3.10]"}
{"when":1723833728,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723833728,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723833729,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723833944,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723833944,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.061s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723833944,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.006s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 71798/71799)"}
{"when":1723833944,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.007s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723833944,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.251s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723833945,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.610s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723833945,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723833945,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723833946,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[71806:python3.10]"}
{"when":1723833951,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723833951,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723833952,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723834411,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723834411,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.073s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723834411,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 82004/82009)"}
{"when":1723834411,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.008s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723834411,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.266s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723834412,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.677s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723834412,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723834412,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723834412,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[82060:python3.10]"}
{"when":1723834430,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723834430,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723834431,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723834911,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723834911,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.052s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723834911,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.004s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 93345/93346)"}
{"when":1723834911,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.006s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723834911,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.273s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723834912,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.655s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723834912,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723834912,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723834913,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[93397:python3.10]"}
{"when":1723834918,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723834918,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723834919,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723834959,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723834959,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.081s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723834959,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.006s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 94465/94467)"}
{"when":1723834959,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.009s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723834959,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.248s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723834960,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.627s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723834960,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723834960,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723834960,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[94517:python3.10]"}
{"when":1723834965,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723834965,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723834966,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723835152,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723835152,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.076s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723835152,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.006s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 98766/98770)"}
{"when":1723835152,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.013s Holotree blueprint is \"66c90dfcc2f61465\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723835152,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.257s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723835153,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.589s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723835153,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723835153,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723835153,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[98820:python3.10]"}
{"when":1723835158,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723835158,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723835159,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723838191,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723838191,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.105s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723838191,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.007s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 67333/67334)"}
{"when":1723838191,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.009s Holotree blueprint is \"b7fcd0f915466811\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723838192,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.306s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723838192,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.716s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723838192,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723838192,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723838193,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[67388:python3.10]"}
{"when":1723838212,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1723838212,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723838213,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723838272,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723838272,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.080s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723838272,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 69149/69150)"}
{"when":1723838272,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.007s Holotree blueprint is \"b7fcd0f915466811\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723838272,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.261s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723838273,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.605s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723838273,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723838273,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723838273,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[69202:python3.10]"}
{"when":1723838279,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723838279,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723838280,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723838434,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723838434,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.094s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723838434,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.007s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 72712/72713)"}
{"when":1723838434,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.007s Holotree blueprint is \"b7fcd0f915466811\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723838434,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.252s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723838434,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.616s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723838434,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723838434,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723838435,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[72758:python3.10]"}
{"when":1723838441,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723838441,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723838442,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723839015,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723839015,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.045s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723839015,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.006s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 87017/87018)"}
{"when":1723839015,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.007s Holotree blueprint is \"56ee48c66f27bd9b\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723839015,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.279s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723839016,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.777s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723839016,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723839016,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723839016,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[87034:python3.10]"}
{"when":1723839073,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723839074,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723839075,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723839202,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723839202,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.040s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723839202,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 91404/91405)"}
{"when":1723839202,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.007s Holotree blueprint is \"56ee48c66f27bd9b\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723839202,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.289s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723839203,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.718s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723839203,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723839203,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723839204,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[91451:python3.10]"}
{"when":1723839212,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723839212,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723839213,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723839288,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723839288,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.071s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723839288,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 93346/93349)"}
{"when":1723839288,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.009s Holotree blueprint is \"56ee48c66f27bd9b\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723839288,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.272s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723839289,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.721s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723839289,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723839289,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723839290,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[93395:python3.10]"}
{"when":1723839298,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723839298,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723839299,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723840490,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723840490,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.048s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723840490,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 20321/20322)"}
{"when":1723840490,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.008s Holotree blueprint is \"56ee48c66f27bd9b\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723840490,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.315s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723840491,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.720s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723840491,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723840491,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723840492,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[20346:python3.10]"}
{"when":1723840523,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 3 ... map[20346:python3.10 21137:bash 21138:Python]"}
{"when":1723840524,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 3 to 4 ... map[20346:python3.10 21137:bash 21138:Python 21153:Python]"}
{"when":1723840524,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 4 to 2 ... map[20346:python3.10 21153:Python]"}
{"when":1723840525,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 3 ... map[20346:python3.10 21199:bash 21200:Python]"}
{"when":1723840526,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 3 to 2 ... map[20346:python3.10 21207:bash]"}
{"when":1723840526,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 1 ... map[20346:python3.10]"}
{"when":1723840527,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1723840527,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723840528,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723840721,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723840722,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.073s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723840722,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 25534/25535)"}
{"when":1723840722,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.010s Holotree blueprint is \"56ee48c66f27bd9b\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723840722,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.319s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723840723,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.686s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723840723,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723840723,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723840723,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[25579:python3.10]"}
{"when":1723840732,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 4 ... map[25579:python3.10 25772:bash 25773:Python 25783:python3.11]"}
{"when":1723840732,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 4 to 1 ... map[25579:python3.10]"}
{"when":1723840733,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[25579:python3.10 25827:bash]"}
{"when":1723840733,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 1 ... map[25579:python3.10]"}
{"when":1723840737,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723840737,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723840738,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723841411,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/og-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723841411,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.100s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723841411,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.006s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 40768/40769)"}
{"when":1723841411,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.011s Holotree blueprint is \"56ee48c66f27bd9b\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723841411,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.261s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723841412,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.708s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723841412,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723841412,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723841412,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[40781:python3.10]"}
{"when":1723841434,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 3 ... map[40781:python3.10 41304:bash 41306:Python]"}
{"when":1723841435,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 3 to 1 ... map[40781:python3.10]"}
{"when":1723841436,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723841436,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723841437,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1723842412,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=/Users/aubreymalabie/Work/iqlabs/recon-base-robot/robot.yaml","comment":"at task environment setup"}
{"when":1723842412,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.049s Context: \"Aubrey Malabie\" \u003caubreymalabie@Aubreys-MacBook-Pro.local\u003e [darwin_amd64/ProductName: macOS; ProductVersion: 14.6.1; BuildVersion: 23G93]."}
{"when":1723842412,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.005s Fresh [shared mode] holotree environment 5751fe1f-e89d-55c5-a85b-0b2718d1872a. (parent/pid: 66452/66453)"}
{"when":1723842412,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.008s Holotree blueprint is \"56ee48c66f27bd9b\" [darwin_amd64 with 9 workers on 10 CPUs from \"conda.yaml\"]."}
{"when":1723842412,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.282s Restore space from library [with 9 workers on 10 CPUs; with compression: true]."}
{"when":1723842413,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.802s Fresh holotree done [with 9 workers on 10 CPUs]."}
{"when":1723842413,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1723842413,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1723842414,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[66518:python3.10]"}
{"when":1723842447,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 3 ... map[66518:python3.10 67575:bash 67577:Python]"}
{"when":1723842448,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 3 to 1 ... map[66518:python3.10]"}
{"when":1723842451,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1723842451,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1723842452,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
